### ISSUE TITLE
Android Support Library Issue

### ISSUE THREAD

**Issue by gsgou** [daniel-luberda/XamarinFormsToolbarCustomFont#1]
In CustomLayoutInflaterFactory.cs and OnCreateView we should replace:
"com.android.internal.view.menu.ActionMenuItemView" with
"android.support.v7.internal.view.menu.ActionMenuItemView"

Instead of ClassLoader.SystemClassLoader.LoadClass
we have to use also PathClassLoader but i haven't found already the right
path for android-support-v7-appcompat.jar. Any suggestions ?

**Comment by daniel-luberda** [comment]
@sgou You should provide you APP APK file location with PathClassLoader. Did you try it?

**Comment by gsgou** [comment]
Thanks Daniel for your prompt response. I tried the following without any success yet:
var pathClassLoader = new PathClassLoader("/data/app/myapk.apk", ClassLoader.SystemClassLoader);
var pathClassLoader = new PathClassLoader("/system/framework/android-support-v7-appcompat.jar", ClassLoader.SystemClassLoader);

**Comment by CR4567** [comment]
Hi guys,

I'm struggling with the same problem. Did you have any success?

**Comment by daniel-luberda** [comment]
@CR4567 @sgou I hadn't time to test it but the easiest thing we could do in that situation is to use `LayoutInflaterCompat.SetFactory` instead https://github.com/daniel-luberda/XamarinFormsToolbarCustomFont/blob/master/Droid/MainActivity.cs#L16

Some examples here: https://github.com/MvvmCross/MvvmCross/issues/981#issuecomment-97442588

If you got any results, let me know.

**Comment by CR4567** [comment]
hi @daniel-luberda,
thx a lot for the quick reply and the possible solution. Unfortunately I'm not very familiar with the construct of the layout inflater....

I tried it like this:
Changed `LayoutInflaterCompat.Factory = new CustomLayoutInflaterFactory();` to 
`var factory = new CustomLayoutInflaterFactory ();`
`using (LayoutInflater layoutInflater = this.LayoutInflater){`
`LayoutInflaterCompat.SetFactory (layoutInflater, (ILayoutInflaterFactory)factory);}`

and changed 
`public class CustomLayoutInflaterFactory : Java.Lang.Object, LayoutInflater.IFactory` to
`public class CustomLayoutInflaterFactory : Java.Lang.Object, ILayoutInflaterFactory`
with the necessary change in the constructor. 
And changed 
`if (!name.Equals("com.android.internal.view.menu.ActionMenuItemView",
                StringComparison.InvariantCultureIgnoreCase)`
to
` if (!name.Equals("android.support.v7.internal.view.menu.ActionMenuItemView",
                StringComparison.InvariantCultureIgnoreCase) 

but it still throws a classNotFoundException...

Sth missing?

**Comment by CR4567** [comment]
hm... still no progress.... don't know what I'm doing wrong. 
every help would be welcome... :-)

**Comment by daniel-luberda** [comment]
@CR4567 I made some initial project for that (not working yet): https://github.com/daniel-luberda/XamarinFormsToolbarCustomFont/commit/8c9bb5ccca61dc13e73323eb4a8e266b6fab40e7 I think I'll get back into soon to get it working (I don't use AppCompat often).

**Comment by CR4567** [comment]
hi @daniel-luberda,
thanks for your input. I was working on a solution the last days but not really getting over it.
Did you have some time to get back to it or could you give me a tip where to start?

**Comment by daniel-luberda** [comment]
@sgou @CR4567 Fixed (see last commit)
