### ISSUE TITLE
Error with FormsAppCompatActivity

### ISSUE THREAD

**Issue by juliengloria** [daniel-luberda/XamarinFormsToolbarCustomFont#2]
Hi,
I'd like  to use your customToolbar with FormsAppCompatActivity but this line throw an exception :
 LayoutInflater.Factory = new CustomLayoutInflaterFactory();

"Java.Lang.IllegalStateException: A factory has already been set on this LayoutInflater"

Could you help me please ?

**Comment by daniel-luberda** [comment]
@ac3ju See this: https://github.com/daniel-luberda/XamarinFormsToolbarCustomFont/issues/1

**Comment by daniel-luberda** [comment]
Fixed (see last commit)
