### ISSUE TITLE
How to make this working on iOS

### ISSUE THREAD

**Issue by alezhuk** [daniel-luberda/XamarinFormsToolbarCustomFont#5]
Hey! That is great sample, but for iOS working needs some small fix.
Just add to your **Info.plist** :

```
<key>UIAppFonts</key>
   <array>
      <string>fontawesome.ttf</string>
   </array>
```

and of course **customFontName** set as **const string customFontName = "fontawesome";**

That's all and not working great for toolbar on iOS.

<img width="368" alt="font_awesome_ios" src="https://cloud.githubusercontent.com/assets/13147031/24172568/5a23e686-0e91-11e7-9e70-767356fcb8c5.png">

**Comment by iChaosren** [comment]
@daniel-luberda 
Can you add this to your README?
Then you can probably close the issue.

**Comment by daniel-luberda** [comment]
Done :) Thanks!
